package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0



/**
 * Customercontact generated by hbm2java
 */
public class Customercontact  implements java.io.Serializable {


     private Integer cconId;
     private Customer customer;
     private String customerEmail;
     private String customerPhoneDay;
     private String customerPhoneNight;

    public Customercontact() {
    }

    public Customercontact(Customer customer, String customerEmail, String customerPhoneDay, String customerPhoneNight) {
       this.customer = customer;
       this.customerEmail = customerEmail;
       this.customerPhoneDay = customerPhoneDay;
       this.customerPhoneNight = customerPhoneNight;
    }
   
    public Integer getCconId() {
        return this.cconId;
    }
    
    public void setCconId(Integer cconId) {
        this.cconId = cconId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
    public String getCustomerPhoneDay() {
        return this.customerPhoneDay;
    }
    
    public void setCustomerPhoneDay(String customerPhoneDay) {
        this.customerPhoneDay = customerPhoneDay;
    }
    public String getCustomerPhoneNight() {
        return this.customerPhoneNight;
    }
    
    public void setCustomerPhoneNight(String customerPhoneNight) {
        this.customerPhoneNight = customerPhoneNight;
    }




}


