package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0



/**
 * Customercredentials generated by hbm2java
 */
public class Customercredentials  implements java.io.Serializable {


     private Integer ccId;
     private Customer customer;
     private String customerLogin;
     private String customerPassword;
     private Integer accountActive;

    public Customercredentials() {
    }

    public Customercredentials(Customer customer, String customerLogin, String customerPassword, Integer accountActive) {
       this.customer = customer;
       this.customerLogin = customerLogin;
       this.customerPassword = customerPassword;
       this.accountActive = accountActive;
    }
   
    public Integer getCcId() {
        return this.ccId;
    }
    
    public void setCcId(Integer ccId) {
        this.ccId = ccId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getCustomerLogin() {
        return this.customerLogin;
    }
    
    public void setCustomerLogin(String customerLogin) {
        this.customerLogin = customerLogin;
    }
    public String getCustomerPassword() {
        return this.customerPassword;
    }
    
    public void setCustomerPassword(String customerPassword) {
        this.customerPassword = customerPassword;
    }
    public Integer getAccountActive() {
        return this.accountActive;
    }
    
    public void setAccountActive(Integer accountActive) {
        this.accountActive = accountActive;
    }




}


