package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer customerId;
     private String firstName;
     private String middleName;
     private String lastName;
     private String gender;
     private Set storeorderses = new HashSet(0);
     private Set customercredentialses = new HashSet(0);
     private Set customercontacts = new HashSet(0);
     private Set shippingaddresses = new HashSet(0);
     private Set billingaddresses = new HashSet(0);

    public Customer() {
    }

    public Customer(String firstName, String middleName, String lastName, String gender, Set storeorderses, Set customercredentialses, Set customercontacts, Set shippingaddresses, Set billingaddresses) {
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.gender = gender;
       this.storeorderses = storeorderses;
       this.customercredentialses = customercredentialses;
       this.customercontacts = customercontacts;
       this.shippingaddresses = shippingaddresses;
       this.billingaddresses = billingaddresses;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Set getStoreorderses() {
        return this.storeorderses;
    }
    
    public void setStoreorderses(Set storeorderses) {
        this.storeorderses = storeorderses;
    }
    public Set getCustomercredentialses() {
        return this.customercredentialses;
    }
    
    public void setCustomercredentialses(Set customercredentialses) {
        this.customercredentialses = customercredentialses;
    }
    public Set getCustomercontacts() {
        return this.customercontacts;
    }
    
    public void setCustomercontacts(Set customercontacts) {
        this.customercontacts = customercontacts;
    }
    public Set getShippingaddresses() {
        return this.shippingaddresses;
    }
    
    public void setShippingaddresses(Set shippingaddresses) {
        this.shippingaddresses = shippingaddresses;
    }
    public Set getBillingaddresses() {
        return this.billingaddresses;
    }
    
    public void setBillingaddresses(Set billingaddresses) {
        this.billingaddresses = billingaddresses;
    }




}


