package com.pojos;
// Generated Nov 9, 2013 6:18:21 PM by Hibernate Tools 3.6.0



/**
 * Orderamounts generated by hbm2java
 */
public class Orderamounts  implements java.io.Serializable {


     private Integer oaId;
     private Storeorders storeorders;
     private Float orderTotal;
     private Float orderSubtotal;
     private Float orderShipping;

    public Orderamounts() {
    }

    public Orderamounts(Storeorders storeorders, Float orderTotal, Float orderSubtotal, Float orderShipping) {
       this.storeorders = storeorders;
       this.orderTotal = orderTotal;
       this.orderSubtotal = orderSubtotal;
       this.orderShipping = orderShipping;
    }
   
    public Integer getOaId() {
        return this.oaId;
    }
    
    public void setOaId(Integer oaId) {
        this.oaId = oaId;
    }
    public Storeorders getStoreorders() {
        return this.storeorders;
    }
    
    public void setStoreorders(Storeorders storeorders) {
        this.storeorders = storeorders;
    }
    public Float getOrderTotal() {
        return this.orderTotal;
    }
    
    public void setOrderTotal(Float orderTotal) {
        this.orderTotal = orderTotal;
    }
    public Float getOrderSubtotal() {
        return this.orderSubtotal;
    }
    
    public void setOrderSubtotal(Float orderSubtotal) {
        this.orderSubtotal = orderSubtotal;
    }
    public Float getOrderShipping() {
        return this.orderShipping;
    }
    
    public void setOrderShipping(Float orderShipping) {
        this.orderShipping = orderShipping;
    }




}


