package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Orderitems generated by hbm2java
 */
public class Orderitems  implements java.io.Serializable {


     private Integer oi;
     private Storeorders storeorders;
     private Product product;
     private Date dateCreated;

    public Orderitems() {
    }

    public Orderitems(Storeorders storeorders, Product product, Date dateCreated) {
       this.storeorders = storeorders;
       this.product = product;
       this.dateCreated = dateCreated;
    }
   
    public Integer getOi() {
        return this.oi;
    }
    
    public void setOi(Integer oi) {
        this.oi = oi;
    }
    public Storeorders getStoreorders() {
        return this.storeorders;
    }
    
    public void setStoreorders(Storeorders storeorders) {
        this.storeorders = storeorders;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


