package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Orderinvoice generated by hbm2java
 */
public class Orderinvoice  implements java.io.Serializable {


     private Integer oiId;
     private Storeorders storeorders;
     private Date invoiceDate;
     private String invoiceStatus;
     private Float invoiceAmount;

    public Orderinvoice() {
    }

    public Orderinvoice(Storeorders storeorders, Date invoiceDate, String invoiceStatus, Float invoiceAmount) {
       this.storeorders = storeorders;
       this.invoiceDate = invoiceDate;
       this.invoiceStatus = invoiceStatus;
       this.invoiceAmount = invoiceAmount;
    }
   
    public Integer getOiId() {
        return this.oiId;
    }
    
    public void setOiId(Integer oiId) {
        this.oiId = oiId;
    }
    public Storeorders getStoreorders() {
        return this.storeorders;
    }
    
    public void setStoreorders(Storeorders storeorders) {
        this.storeorders = storeorders;
    }
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public String getInvoiceStatus() {
        return this.invoiceStatus;
    }
    
    public void setInvoiceStatus(String invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    public Float getInvoiceAmount() {
        return this.invoiceAmount;
    }
    
    public void setInvoiceAmount(Float invoiceAmount) {
        this.invoiceAmount = invoiceAmount;
    }




}


