package com.pojos;
// Generated Nov 9, 2013 6:18:21 PM by Hibernate Tools 3.6.0



/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails  implements java.io.Serializable {


     private Integer odId;
     private Storeorders storeorders;
     private String orderComments;
     private String orderIp;
     private Float orderTaxRate;

    public Orderdetails() {
    }

    public Orderdetails(Storeorders storeorders, String orderComments, String orderIp, Float orderTaxRate) {
       this.storeorders = storeorders;
       this.orderComments = orderComments;
       this.orderIp = orderIp;
       this.orderTaxRate = orderTaxRate;
    }
   
    public Integer getOdId() {
        return this.odId;
    }
    
    public void setOdId(Integer odId) {
        this.odId = odId;
    }
    public Storeorders getStoreorders() {
        return this.storeorders;
    }
    
    public void setStoreorders(Storeorders storeorders) {
        this.storeorders = storeorders;
    }
    public String getOrderComments() {
        return this.orderComments;
    }
    
    public void setOrderComments(String orderComments) {
        this.orderComments = orderComments;
    }
    public String getOrderIp() {
        return this.orderIp;
    }
    
    public void setOrderIp(String orderIp) {
        this.orderIp = orderIp;
    }
    public Float getOrderTaxRate() {
        return this.orderTaxRate;
    }
    
    public void setOrderTaxRate(Float orderTaxRate) {
        this.orderTaxRate = orderTaxRate;
    }




}


