package com.pojos;
// Generated Nov 9, 2013 6:18:21 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer productId;
     private StoreCategories storeCategories;
     private String productName;
     private String productSku;
     private String productDescr;
     private Set productdims = new HashSet(0);
     private Set orderitemses = new HashSet(0);
     private Set productinventories = new HashSet(0);
     private Set productpriceses = new HashSet(0);
     private Set productdetails = new HashSet(0);
     private Set productshippingpropses = new HashSet(0);
     private Set productcustomattrs = new HashSet(0);

    public Product() {
    }

    public Product(StoreCategories storeCategories, String productName, String productSku, String productDescr, Set productdims, Set orderitemses, Set productinventories, Set productpriceses, Set productdetails, Set productshippingpropses, Set productcustomattrs) {
       this.storeCategories = storeCategories;
       this.productName = productName;
       this.productSku = productSku;
       this.productDescr = productDescr;
       this.productdims = productdims;
       this.orderitemses = orderitemses;
       this.productinventories = productinventories;
       this.productpriceses = productpriceses;
       this.productdetails = productdetails;
       this.productshippingpropses = productshippingpropses;
       this.productcustomattrs = productcustomattrs;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public StoreCategories getStoreCategories() {
        return this.storeCategories;
    }
    
    public void setStoreCategories(StoreCategories storeCategories) {
        this.storeCategories = storeCategories;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getProductSku() {
        return this.productSku;
    }
    
    public void setProductSku(String productSku) {
        this.productSku = productSku;
    }
    public String getProductDescr() {
        return this.productDescr;
    }
    
    public void setProductDescr(String productDescr) {
        this.productDescr = productDescr;
    }
    public Set getProductdims() {
        return this.productdims;
    }
    
    public void setProductdims(Set productdims) {
        this.productdims = productdims;
    }
    public Set getOrderitemses() {
        return this.orderitemses;
    }
    
    public void setOrderitemses(Set orderitemses) {
        this.orderitemses = orderitemses;
    }
    public Set getProductinventories() {
        return this.productinventories;
    }
    
    public void setProductinventories(Set productinventories) {
        this.productinventories = productinventories;
    }
    public Set getProductpriceses() {
        return this.productpriceses;
    }
    
    public void setProductpriceses(Set productpriceses) {
        this.productpriceses = productpriceses;
    }
    public Set getProductdetails() {
        return this.productdetails;
    }
    
    public void setProductdetails(Set productdetails) {
        this.productdetails = productdetails;
    }
    public Set getProductshippingpropses() {
        return this.productshippingpropses;
    }
    
    public void setProductshippingpropses(Set productshippingpropses) {
        this.productshippingpropses = productshippingpropses;
    }
    public Set getProductcustomattrs() {
        return this.productcustomattrs;
    }
    
    public void setProductcustomattrs(Set productcustomattrs) {
        this.productcustomattrs = productcustomattrs;
    }




}


