package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0



/**
 * Productinventory generated by hbm2java
 */
public class Productinventory  implements java.io.Serializable {


     private Integer piId;
     private Product product;
     private Integer inventoryCount;
     private Integer backOrder;
     private Integer discontinued;

    public Productinventory() {
    }

    public Productinventory(Product product, Integer inventoryCount, Integer backOrder, Integer discontinued) {
       this.product = product;
       this.inventoryCount = inventoryCount;
       this.backOrder = backOrder;
       this.discontinued = discontinued;
    }
   
    public Integer getPiId() {
        return this.piId;
    }
    
    public void setPiId(Integer piId) {
        this.piId = piId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getInventoryCount() {
        return this.inventoryCount;
    }
    
    public void setInventoryCount(Integer inventoryCount) {
        this.inventoryCount = inventoryCount;
    }
    public Integer getBackOrder() {
        return this.backOrder;
    }
    
    public void setBackOrder(Integer backOrder) {
        this.backOrder = backOrder;
    }
    public Integer getDiscontinued() {
        return this.discontinued;
    }
    
    public void setDiscontinued(Integer discontinued) {
        this.discontinued = discontinued;
    }




}


