package com.pojos;
// Generated Nov 9, 2013 6:18:21 PM by Hibernate Tools 3.6.0



/**
 * Productshippingprops generated by hbm2java
 */
public class Productshippingprops  implements java.io.Serializable {


     private Integer pspId;
     private Product product;
     private Integer freeShipping;
     private Float shippingWeight;
     private Integer shipable;

    public Productshippingprops() {
    }

    public Productshippingprops(Product product, Integer freeShipping, Float shippingWeight, Integer shipable) {
       this.product = product;
       this.freeShipping = freeShipping;
       this.shippingWeight = shippingWeight;
       this.shipable = shipable;
    }
   
    public Integer getPspId() {
        return this.pspId;
    }
    
    public void setPspId(Integer pspId) {
        this.pspId = pspId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Integer getFreeShipping() {
        return this.freeShipping;
    }
    
    public void setFreeShipping(Integer freeShipping) {
        this.freeShipping = freeShipping;
    }
    public Float getShippingWeight() {
        return this.shippingWeight;
    }
    
    public void setShippingWeight(Float shippingWeight) {
        this.shippingWeight = shippingWeight;
    }
    public Integer getShipable() {
        return this.shipable;
    }
    
    public void setShipable(Integer shipable) {
        this.shipable = shipable;
    }




}


