package com.pojos;
// Generated Nov 9, 2013 6:18:21 PM by Hibernate Tools 3.6.0



/**
 * Productprices generated by hbm2java
 */
public class Productprices  implements java.io.Serializable {


     private Integer ppId;
     private Product product;
     private Float producPrice;
     private Float specialPrice;
     private Float productCost;

    public Productprices() {
    }

    public Productprices(Product product, Float producPrice, Float specialPrice, Float productCost) {
       this.product = product;
       this.producPrice = producPrice;
       this.specialPrice = specialPrice;
       this.productCost = productCost;
    }
   
    public Integer getPpId() {
        return this.ppId;
    }
    
    public void setPpId(Integer ppId) {
        this.ppId = ppId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Float getProducPrice() {
        return this.producPrice;
    }
    
    public void setProducPrice(Float producPrice) {
        this.producPrice = producPrice;
    }
    public Float getSpecialPrice() {
        return this.specialPrice;
    }
    
    public void setSpecialPrice(Float specialPrice) {
        this.specialPrice = specialPrice;
    }
    public Float getProductCost() {
        return this.productCost;
    }
    
    public void setProductCost(Float productCost) {
        this.productCost = productCost;
    }




}


