package com.pojos;
// Generated Nov 9, 2013 6:18:21 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Storeorders generated by hbm2java
 */
public class Storeorders  implements java.io.Serializable {


     private Integer orderId;
     private Customer customer;
     private Integer orderNumber;
     private Date orderDate;
     private Float orderTotal;
     private String storeorderscol;
     private Set orderstatuses = new HashSet(0);
     private Set orderinvoices = new HashSet(0);
     private Set orderdetailses = new HashSet(0);
     private Set orderitemses = new HashSet(0);
     private Set orderamountses = new HashSet(0);

    public Storeorders() {
    }

    public Storeorders(Customer customer, Integer orderNumber, Date orderDate, Float orderTotal, String storeorderscol, Set orderstatuses, Set orderinvoices, Set orderdetailses, Set orderitemses, Set orderamountses) {
       this.customer = customer;
       this.orderNumber = orderNumber;
       this.orderDate = orderDate;
       this.orderTotal = orderTotal;
       this.storeorderscol = storeorderscol;
       this.orderstatuses = orderstatuses;
       this.orderinvoices = orderinvoices;
       this.orderdetailses = orderdetailses;
       this.orderitemses = orderitemses;
       this.orderamountses = orderamountses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Integer getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Float getOrderTotal() {
        return this.orderTotal;
    }
    
    public void setOrderTotal(Float orderTotal) {
        this.orderTotal = orderTotal;
    }
    public String getStoreorderscol() {
        return this.storeorderscol;
    }
    
    public void setStoreorderscol(String storeorderscol) {
        this.storeorderscol = storeorderscol;
    }
    public Set getOrderstatuses() {
        return this.orderstatuses;
    }
    
    public void setOrderstatuses(Set orderstatuses) {
        this.orderstatuses = orderstatuses;
    }
    public Set getOrderinvoices() {
        return this.orderinvoices;
    }
    
    public void setOrderinvoices(Set orderinvoices) {
        this.orderinvoices = orderinvoices;
    }
    public Set getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set orderdetailses) {
        this.orderdetailses = orderdetailses;
    }
    public Set getOrderitemses() {
        return this.orderitemses;
    }
    
    public void setOrderitemses(Set orderitemses) {
        this.orderitemses = orderitemses;
    }
    public Set getOrderamountses() {
        return this.orderamountses;
    }
    
    public void setOrderamountses(Set orderamountses) {
        this.orderamountses = orderamountses;
    }




}


