package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * StoreCategories generated by hbm2java
 */
public class StoreCategories  implements java.io.Serializable {


     private Integer catId;
     private String catDescription;
     private byte[] catPicture;
     private Integer catActive;
     private String catSearchable;
     private String catName;
     private Set products = new HashSet(0);

    public StoreCategories() {
    }

	
    public StoreCategories(String catName) {
        this.catName = catName;
    }
    public StoreCategories(String catDescription, byte[] catPicture, Integer catActive, String catSearchable, String catName, Set products) {
       this.catDescription = catDescription;
       this.catPicture = catPicture;
       this.catActive = catActive;
       this.catSearchable = catSearchable;
       this.catName = catName;
       this.products = products;
    }
   
    public Integer getCatId() {
        return this.catId;
    }
    
    public void setCatId(Integer catId) {
        this.catId = catId;
    }
    public String getCatDescription() {
        return this.catDescription;
    }
    
    public void setCatDescription(String catDescription) {
        this.catDescription = catDescription;
    }
    public byte[] getCatPicture() {
        return this.catPicture;
    }
    
    public void setCatPicture(byte[] catPicture) {
        this.catPicture = catPicture;
    }
    public Integer getCatActive() {
        return this.catActive;
    }
    
    public void setCatActive(Integer catActive) {
        this.catActive = catActive;
    }
    public String getCatSearchable() {
        return this.catSearchable;
    }
    
    public void setCatSearchable(String catSearchable) {
        this.catSearchable = catSearchable;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


