package com.pojos;
// Generated Nov 1, 2013 7:16:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Useradmin generated by hbm2java
 */
public class Useradmin  implements java.io.Serializable {


     private int uaId;
     private String firstName;
     private String middleName;
     private String lastName;
     private String displayName;
     private Set admincredentialses = new HashSet(0);

    public Useradmin() {
    }

	
    public Useradmin(int uaId) {
        this.uaId = uaId;
    }
    public Useradmin(int uaId, String firstName, String middleName, String lastName, String displayName, Set admincredentialses) {
       this.uaId = uaId;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.displayName = displayName;
       this.admincredentialses = admincredentialses;
    }
   
    public int getUaId() {
        return this.uaId;
    }
    
    public void setUaId(int uaId) {
        this.uaId = uaId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Set getAdmincredentialses() {
        return this.admincredentialses;
    }
    
    public void setAdmincredentialses(Set admincredentialses) {
        this.admincredentialses = admincredentialses;
    }




}


