
package ws_creditcard;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardCheckWS", targetNamespace = "http://WS_CreditCard/", wsdlLocation = "http://localhost:8060/CreditCardVerificationWS/VerifyCard?wsdl")
public class CardCheckWS_Service
    extends Service
{

    private final static URL CARDCHECKWS_WSDL_LOCATION;
    private final static WebServiceException CARDCHECKWS_EXCEPTION;
    private final static QName CARDCHECKWS_QNAME = new QName("http://WS_CreditCard/", "CardCheckWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8060/CreditCardVerificationWS/VerifyCard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDCHECKWS_WSDL_LOCATION = url;
        CARDCHECKWS_EXCEPTION = e;
    }

    public CardCheckWS_Service() {
        super(__getWsdlLocation(), CARDCHECKWS_QNAME);
    }

    public CardCheckWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDCHECKWS_QNAME, features);
    }

    public CardCheckWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CARDCHECKWS_QNAME);
    }

    public CardCheckWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDCHECKWS_QNAME, features);
    }

    public CardCheckWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardCheckWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardCheckWS
     */
    @WebEndpoint(name = "CardCheckWSPort")
    public CardCheckWS getCardCheckWSPort() {
        return super.getPort(new QName("http://WS_CreditCard/", "CardCheckWSPort"), CardCheckWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardCheckWS
     */
    @WebEndpoint(name = "CardCheckWSPort")
    public CardCheckWS getCardCheckWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WS_CreditCard/", "CardCheckWSPort"), CardCheckWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDCHECKWS_EXCEPTION!= null) {
            throw CARDCHECKWS_EXCEPTION;
        }
        return CARDCHECKWS_WSDL_LOCATION;
    }

}
