
package com.emart.creditvalid;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditCardVerification", targetNamespace = "http://creditValid.emart.com/", wsdlLocation = "http://localhost:8089/CreditCardVerification/CreditCardVerification?wsdl")
public class CreditCardVerification_Service
    extends Service
{

    private final static URL CREDITCARDVERIFICATION_WSDL_LOCATION;
    private final static WebServiceException CREDITCARDVERIFICATION_EXCEPTION;
    private final static QName CREDITCARDVERIFICATION_QNAME = new QName("http://creditValid.emart.com/", "CreditCardVerification");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/CreditCardVerification/CreditCardVerification?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITCARDVERIFICATION_WSDL_LOCATION = url;
        CREDITCARDVERIFICATION_EXCEPTION = e;
    }

    public CreditCardVerification_Service() {
        super(__getWsdlLocation(), CREDITCARDVERIFICATION_QNAME);
    }

    public CreditCardVerification_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITCARDVERIFICATION_QNAME, features);
    }

    public CreditCardVerification_Service(URL wsdlLocation) {
        super(wsdlLocation, CREDITCARDVERIFICATION_QNAME);
    }

    public CreditCardVerification_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITCARDVERIFICATION_QNAME, features);
    }

    public CreditCardVerification_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardVerification_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditCardVerification
     */
    @WebEndpoint(name = "CreditCardVerificationPort")
    public CreditCardVerification getCreditCardVerificationPort() {
        return super.getPort(new QName("http://creditValid.emart.com/", "CreditCardVerificationPort"), CreditCardVerification.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardVerification
     */
    @WebEndpoint(name = "CreditCardVerificationPort")
    public CreditCardVerification getCreditCardVerificationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://creditValid.emart.com/", "CreditCardVerificationPort"), CreditCardVerification.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITCARDVERIFICATION_EXCEPTION!= null) {
            throw CREDITCARDVERIFICATION_EXCEPTION;
        }
        return CREDITCARDVERIFICATION_WSDL_LOCATION;
    }

}
