
package com.emart.creditvalid;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditCardVerification", targetNamespace = "http://creditValid.emart.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditCardVerification {


    /**
     * 
     * @param cardNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyCard", targetNamespace = "http://creditValid.emart.com/", className = "com.emart.creditvalid.VerifyCard")
    @ResponseWrapper(localName = "verifyCardResponse", targetNamespace = "http://creditValid.emart.com/", className = "com.emart.creditvalid.VerifyCardResponse")
    @Action(input = "http://creditValid.emart.com/CreditCardVerification/verifyCardRequest", output = "http://creditValid.emart.com/CreditCardVerification/verifyCardResponse")
    public String verifyCard(
        @WebParam(name = "cardNum", targetNamespace = "")
        String cardNum);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ismod10", targetNamespace = "http://creditValid.emart.com/", className = "com.emart.creditvalid.Ismod10")
    @ResponseWrapper(localName = "ismod10Response", targetNamespace = "http://creditValid.emart.com/", className = "com.emart.creditvalid.Ismod10Response")
    @Action(input = "http://creditValid.emart.com/CreditCardVerification/ismod10Request", output = "http://creditValid.emart.com/CreditCardVerification/ismod10Response")
    public boolean ismod10(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0);

}
